const container = document.querySelector(".container")
const qrCodeBtn = document.querySelector("#qr-form button")
const qrCodeInput = document.querySelector("#qr-form input")
const qrCodeImg = document.querySelector("#qr-code img")

// Generate the QR Code
function generateQrCode() {
    const qrCodeInputValue = qrCodeInput.value;
    // Validation if the Input value is empty.
    if (!qrCodeInputValue) return;
    // Loading Text awaiting for API response.
    qrCodeBtn.innerText = "Generating Qr...";
    // Replaces the default image with the QR generated by the API, the value is retrieved from the Input Value.
    qrCodeImg.src = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${qrCodeInputValue}`;
    // Replaces the default image with the QR generated by the API, the value is retrieved from the Input Value.
    qrCodeImg.addEventListener("load", () => {
        container.classList.add("active");
        qrCodeBtn.innerText = "QR Created !";
    });
}

// Clear the QR Code area
qrCodeInput.addEventListener("keyup", () => {
    if(!qrCodeInput.value) {
        container.classList.remove("active");
        qrCodeBtn.innerText = "Generate QR Code";
    }
})

// Events 
qrCodeBtn.addEventListener("click", () => {
    generateQrCode();
})

qrCodeInput.addEventListener("keydown", (e) => {
    if(e.code === "Enter") {
        generateQrCode();
    }
})